# Generated by Django 2.1.1 on 2018-09-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('flight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('airline_id', models.IntegerField()),
                ('airline_name', models.CharField(max_length=15)),
                ('from_loc', models.CharField(max_length=20)),
                ('to_loc', models.CharField(max_length=20)),
                ('dep_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=4)),
                ('no_seats', models.IntegerField(max_length=100)),
            ],
        ),
    ]
