# Generated by Django 2.1.1 on 2018-09-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_flight_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_details',
            name='flight_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
    ]
