# Generated by Django 2.1.1 on 2018-09-21 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flight_details_flight_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField()),
                ('card_type', models.CharField(max_length=20)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='passenger_info',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('tel_no', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_info',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flight_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('rofile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.passenger_info')),
            ],
        ),
        migrations.AddField(
            model_name='card_details',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.passenger_info'),
        ),
    ]
